window.TEST_MODEL = {
  title: "Unvalidated Personality Test",
  responseScale: [
    { value: 1, label: "Strongly disagree" },
    { value: 2, label: "Disagree" },
    { value: 3, label: "Neither" },
    { value: 4, label: "Agree" },
    { value: 5, label: "Strongly agree" }
  ],
  traits: {
    socialEnergy: { name: "Social Energy", group: "People", low: "Solitude-seeking", high: "Interaction-seeking", description: "How strongly you tend to seek stimulation and momentum from being around other people." },
    socialBoldness: { name: "Social Boldness", group: "People", low: "Reserved", high: "Forward", description: "How readily you enter unfamiliar social situations, speak up, and tolerate being noticed." },
    influence: { name: "Influence", group: "People", low: "Non-directive", high: "Persuasive", description: "How much you enjoy shaping decisions, arguing a case, or moving a group toward your preferred direction." },
    cooperativeness: { name: "Cooperativeness", group: "People", low: "Hard-edged", high: "Accommodating", description: "How naturally you make room for other people’s preferences and preserve working harmony." },
    empathicAttention: { name: "Empathic Attention", group: "People", low: "Detached", high: "Attuned", description: "How much attention you give to other people’s emotional signals and unspoken reactions." },
    structure: { name: "Structure", group: "Execution", low: "Improvisational", high: "Systematic", description: "How strongly you prefer plans, order, routines, and clearly arranged work." },
    persistence: { name: "Persistence", group: "Execution", low: "Quick to disengage", high: "Tenacious", description: "How readily you keep effort going after novelty fades or obstacles appear." },
    adaptability: { name: "Adaptability", group: "Execution", low: "Continuity-seeking", high: "Change-ready", description: "How comfortably you revise plans, switch methods, and absorb unexpected changes." },
    analyticalCuriosity: { name: "Analytical Curiosity", group: "Thinking", low: "Intuitive", high: "Analytical", description: "How much you enjoy examining assumptions, mechanisms, evidence, and logical structure." },
    imagination: { name: "Imagination", group: "Thinking", low: "Concrete", high: "Possibility-oriented", description: "How naturally you generate unusual possibilities, speculative ideas, and alternative ways of seeing things." },
    decisiveness: { name: "Decisiveness", group: "Temperament", low: "Deliberative", high: "Quick-committing", description: "How readily you commit to a course of action when information is incomplete." },
    emotionalSteadiness: { name: "Emotional Steadiness", group: "Temperament", low: "Reactive", high: "Even-keeled", description: "How consistently you stay composed and recover your equilibrium when pressure rises." }
  },
  items: [
    { id: 1, trait: "socialEnergy", reverse: false, text: "After a long stretch with people, I often still have energy for more conversation." },
    { id: 2, trait: "structure", reverse: false, text: "I feel better about a task once I have given it a clear sequence or plan." },
    { id: 3, trait: "analyticalCuriosity", reverse: false, text: "When someone makes a confident claim, I instinctively wonder what evidence would change their mind." },
    { id: 4, trait: "cooperativeness", reverse: true, text: "If I think my approach is better, I see little reason to adjust it for someone else's preference." },
    { id: 5, trait: "emotionalSteadiness", reverse: false, text: "Under pressure, I can usually keep one setback from colouring the rest of my day." },
    { id: 6, trait: "imagination", reverse: false, text: "I enjoy exploring ideas that are interesting even when they have no immediate practical use." },
    { id: 7, trait: "socialBoldness", reverse: false, text: "I am comfortable being the first person to introduce myself in an unfamiliar group." },
    { id: 8, trait: "persistence", reverse: false, text: "I can keep working steadily on something long after the interesting part is over." },
    { id: 9, trait: "influence", reverse: false, text: "I enjoy making a case strongly enough that other people reconsider their position." },
    { id: 10, trait: "adaptability", reverse: false, text: "A last-minute change of plan usually feels more like a puzzle than a disruption." },
    { id: 11, trait: "empathicAttention", reverse: false, text: "I often notice that someone's mood has shifted before they say anything about it." },
    { id: 12, trait: "decisiveness", reverse: true, text: "I prefer to postpone a decision if there is a realistic chance that more information will appear." },
    { id: 13, trait: "socialEnergy", reverse: true, text: "Even enjoyable social events tend to leave me wanting a substantial amount of time alone." },
    { id: 14, trait: "structure", reverse: true, text: "Detailed plans often feel like unnecessary constraints on how I work." },
    { id: 15, trait: "analyticalCuriosity", reverse: true, text: "If an explanation sounds plausible, I rarely feel a need to inspect how it works underneath." },
    { id: 16, trait: "cooperativeness", reverse: false, text: "I will often accept a second-best option if it makes a group work together more smoothly." },
    { id: 17, trait: "emotionalSteadiness", reverse: true, text: "Small frustrations can stay with me for longer than I would like." },
    { id: 18, trait: "imagination", reverse: true, text: "I lose patience when conversations spend too long on hypothetical possibilities." },
    { id: 19, trait: "socialBoldness", reverse: true, text: "When I enter a room where I know almost nobody, I prefer to let others make the first move." },
    { id: 20, trait: "persistence", reverse: true, text: "Once a task becomes repetitive, my effort tends to drop quickly." },
    { id: 21, trait: "influence", reverse: true, text: "I usually avoid trying to change people's minds, even when I disagree strongly." },
    { id: 22, trait: "adaptability", reverse: true, text: "I find it irritating when I have prepared carefully and the plan changes anyway." },
    { id: 23, trait: "empathicAttention", reverse: true, text: "I tend to take people's words at face value rather than look for emotional subtext." },
    { id: 24, trait: "decisiveness", reverse: false, text: "When several options are all reasonable, I can choose one without much lingering doubt." },
    { id: 25, trait: "socialEnergy", reverse: false, text: "I naturally look for chances to turn solitary activities into shared ones." },
    { id: 26, trait: "structure", reverse: false, text: "I like having a reliable system for keeping track of small commitments." },
    { id: 27, trait: "analyticalCuriosity", reverse: false, text: "I enjoy finding the hidden assumption that makes an argument succeed or fail." },
    { id: 28, trait: "cooperativeness", reverse: false, text: "When tension rises in a group, I usually start looking for a workable middle ground." },
    { id: 29, trait: "emotionalSteadiness", reverse: false, text: "I can receive blunt criticism without immediately becoming defensive." },
    { id: 30, trait: "imagination", reverse: false, text: "My mind often produces alternative explanations or possibilities without being asked to." },
    { id: 31, trait: "socialBoldness", reverse: false, text: "Speaking to a room full of people feels manageable even when I have not had much time to prepare." },
    { id: 32, trait: "persistence", reverse: false, text: "If I decide something matters, slow progress rarely makes me abandon it." },
    { id: 33, trait: "influence", reverse: false, text: "In group decisions, I am comfortable pushing for the option I think is strongest." },
    { id: 34, trait: "adaptability", reverse: false, text: "I can switch between very different tasks without needing much time to mentally reset." },
    { id: 35, trait: "empathicAttention", reverse: false, text: "I adjust how I say something when I sense that the other person is uneasy or discouraged." },
    { id: 36, trait: "decisiveness", reverse: false, text: "I would rather make a sensible decision now than keep improving the decision indefinitely." },
    { id: 37, trait: "socialEnergy", reverse: true, text: "When I have free time, my default preference is usually to spend it by myself." },
    { id: 38, trait: "structure", reverse: true, text: "I often rely on memory rather than lists, reminders, or organised systems." },
    { id: 39, trait: "analyticalCuriosity", reverse: true, text: "I care more about whether an idea feels useful than whether the reasoning behind it is rigorous." },
    { id: 40, trait: "cooperativeness", reverse: true, text: "Compromise often seems like a poor substitute for deciding which side is actually right." },
    { id: 41, trait: "emotionalSteadiness", reverse: true, text: "When several things go wrong at once, my reactions can become noticeably sharper." },
    { id: 42, trait: "imagination", reverse: true, text: "I prefer discussions to stay close to concrete facts and immediate realities." },
    { id: 43, trait: "socialBoldness", reverse: true, text: "I hesitate to express an unpopular opinion when I do not yet know the group well." },
    { id: 44, trait: "persistence", reverse: true, text: "If repeated attempts do not work, I am usually eager to move on to something else." },
    { id: 45, trait: "influence", reverse: true, text: "I am happiest contributing ideas without needing to steer the final decision." },
    { id: 46, trait: "adaptability", reverse: true, text: "Once I have settled into an approach, changing methods costs me a lot of momentum." },
    { id: 47, trait: "empathicAttention", reverse: true, text: "Other people's subtle changes in tone or expression often pass me by." },
    { id: 48, trait: "decisiveness", reverse: true, text: "After making an important choice, I often reopen the question in my head." },
    { id: 49, trait: "socialEnergy", reverse: false, text: "A lively group usually increases my energy rather than draining it." },
    { id: 50, trait: "structure", reverse: false, text: "I prefer to finish arranging the details of a task before I fully relax about it." },
    { id: 51, trait: "analyticalCuriosity", reverse: false, text: "I like comparing competing explanations to see which one accounts for more of the evidence." },
    { id: 52, trait: "cooperativeness", reverse: false, text: "I make a deliberate effort not to turn ordinary disagreements into contests." },
    { id: 53, trait: "emotionalSteadiness", reverse: false, text: "Unexpected problems rarely make me feel that everything is suddenly going badly." },
    { id: 54, trait: "imagination", reverse: false, text: "I enjoy combining ideas from unrelated areas to see what new angle appears." },
    { id: 55, trait: "socialBoldness", reverse: false, text: "I am comfortable asking a question that might reveal I have misunderstood something." },
    { id: 56, trait: "persistence", reverse: false, text: "I am willing to repeat an unglamorous process many times if that is what improvement requires." },
    { id: 57, trait: "influence", reverse: false, text: "If a discussion is drifting, I often try to give it a direction." },
    { id: 58, trait: "adaptability", reverse: false, text: "I can change my mind without feeling that I have lost face." },
    { id: 59, trait: "empathicAttention", reverse: false, text: "I often think about how a decision will feel from the other person's side, not only what it will do." },
    { id: 60, trait: "decisiveness", reverse: false, text: "I can act on an imperfect answer when waiting has a real cost." },
    { id: 61, trait: "socialEnergy", reverse: true, text: "Several hours of conversation usually makes quiet time feel especially appealing." },
    { id: 62, trait: "structure", reverse: true, text: "I am comfortable starting complex work without deciding in advance how I will organise it." },
    { id: 63, trait: "analyticalCuriosity", reverse: true, text: "I rarely investigate why a system behaves the way it does unless I need to fix it." },
    { id: 64, trait: "cooperativeness", reverse: true, text: "When I know I am right, preserving harmony is not much of a priority for me." },
    { id: 65, trait: "emotionalSteadiness", reverse: true, text: "A tense interaction can occupy my thoughts for quite a while afterwards." },
    { id: 66, trait: "imagination", reverse: true, text: "I would rather improve an existing idea than invent a completely different one." },
    { id: 67, trait: "socialBoldness", reverse: true, text: "I prefer to watch how a new group works before drawing attention to myself." },
    { id: 68, trait: "persistence", reverse: true, text: "When a goal requires months of small steps, I find it hard to maintain the same commitment." },
    { id: 69, trait: "influence", reverse: true, text: "I tend to keep my preferred outcome to myself unless someone explicitly asks." },
    { id: 70, trait: "adaptability", reverse: true, text: "Frequent switching between priorities makes it difficult for me to do my best work." },
    { id: 71, trait: "empathicAttention", reverse: true, text: "I am more likely to focus on what someone said than on how they seemed to feel while saying it." },
    { id: 72, trait: "decisiveness", reverse: true, text: "I can spend too long looking for one more reason before committing to a choice." }
  ]
};